# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: servizi.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservizi.proto\x12\x07servizi\"(\n\x08\x41rticolo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08prodotto\x18\x02 \x01(\t\"\x1a\n\x05\x45sito\x12\x11\n\tmessaggio\x18\x01 \x01(\t\"\x1e\n\tRichiesta\x12\x11\n\tmessaggio\x18\x01 \x01(\t2\x99\x01\n\x08\x46unzioni\x12-\n\x08\x44\x65posita\x12\x11.servizi.Articolo\x1a\x0e.servizi.Esito\x12\x30\n\x07Preleva\x12\x12.servizi.Richiesta\x1a\x11.servizi.Articolo\x12,\n\x06Svuota\x12\x12.servizi.Richiesta\x1a\x0e.servizi.Esitob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'servizi_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ARTICOLO']._serialized_start=26
  _globals['_ARTICOLO']._serialized_end=66
  _globals['_ESITO']._serialized_start=68
  _globals['_ESITO']._serialized_end=94
  _globals['_RICHIESTA']._serialized_start=96
  _globals['_RICHIESTA']._serialized_end=126
  _globals['_FUNZIONI']._serialized_start=129
  _globals['_FUNZIONI']._serialized_end=282
# @@protoc_insertion_point(module_scope)
