# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: servizi.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservizi.proto\x12\x07servizi\"!\n\x08Prodotto\x12\x15\n\rserial_number\x18\x01 \x01(\x05\"\x14\n\x03\x41\x63k\x12\r\n\x05\x65sito\x18\x01 \x01(\x08\"\x1a\n\x05Vuoto\x12\x11\n\tmessaggio\x18\x01 \x01(\t2]\n\x08\x46unzioni\x12(\n\x03\x42uy\x12\x0e.servizi.Vuoto\x1a\x11.servizi.Prodotto\x12\'\n\x04Sell\x12\x11.servizi.Prodotto\x1a\x0c.servizi.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'servizi_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODOTTO']._serialized_start=26
  _globals['_PRODOTTO']._serialized_end=59
  _globals['_ACK']._serialized_start=61
  _globals['_ACK']._serialized_end=81
  _globals['_VUOTO']._serialized_start=83
  _globals['_VUOTO']._serialized_end=109
  _globals['_FUNZIONI']._serialized_start=111
  _globals['_FUNZIONI']._serialized_end=204
# @@protoc_insertion_point(module_scope)
