# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: servizi.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservizi.proto\x12\x07servizi\"\x1a\n\x05\x45mpty\x12\x11\n\tmessaggio\x18\x01 \x01(\t\"\'\n\x06Sensor\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tdata_type\x18\x02 \x01(\t\"3\n\x0bMeanRequest\x12\x11\n\tsensor_id\x18\x01 \x01(\x05\x12\x11\n\tdata_type\x18\x02 \x01(\t\"&\n\rStringMessage\x12\x15\n\rcalcolo_media\x18\x01 \x01(\x02\x32t\n\x08\x46unzioni\x12/\n\ngetSensors\x12\x0e.servizi.Empty\x1a\x0f.servizi.Sensor0\x01\x12\x37\n\x07getMean\x12\x14.servizi.MeanRequest\x1a\x16.servizi.StringMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'servizi_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=26
  _globals['_EMPTY']._serialized_end=52
  _globals['_SENSOR']._serialized_start=54
  _globals['_SENSOR']._serialized_end=93
  _globals['_MEANREQUEST']._serialized_start=95
  _globals['_MEANREQUEST']._serialized_end=146
  _globals['_STRINGMESSAGE']._serialized_start=148
  _globals['_STRINGMESSAGE']._serialized_end=186
  _globals['_FUNZIONI']._serialized_start=188
  _globals['_FUNZIONI']._serialized_end=304
# @@protoc_insertion_point(module_scope)
